akurdion/urls.py
from django.urls import path
from .views import index

app_name = 'akurdion'

urlpatterns = [
    path('', index, name='index'),
]

donotopen/urls.py
from django.urls import path
from .views import index, register
from django.contrib.auth import views as auth_views

app_name = 'donotopen'

urlpatterns = [
    path('', index, name='index'),
    path('register/', register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='donotopen/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='donotopen/logout.html'), name='logout'),
]

fesbuk/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('vline/', include("vline.urls")),
    path('akurdion/', include("akurdion.urls")),
    path('book/', include("ijustnameitbookbecauseimnotcreative.urls")),
    path('donotopen/', include("donotopen.urls")),
]

ijustnameitbookbecauseimnotcreative/urls.py
from django.urls import path
from .views import index

app_name = 'book'

urlpatterns = [
    path('', index, name='index'),
]

vline/urls.py
from django.urls import path
from .views import index, addmessage

app_name = 'vline'

urlpatterns = [
    path('', index, name='index'),
    path('addmessage', addmessage, name='addmessage')
]

akurdion/models.py
from django.db import models

class Content(models.Model):
    title = models.CharField(max_length=60)
    content = models.TextField()

    def __str__(self):
        return self.title

donotopen/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserCustom(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.CharField(default='http://getdrawings.com/img/facebook-profile-picture-silhouette-female-18.jpg', max_length=500)

    def __str__(self):
        return self.user.username

ijustnameitbookbecauseimnotcreative/models.py
from django.db import models

# Create your models here.
class Book(models.Model):
    id = models.CharField(max_length=100, primary_key=True, unique=True)
    title = models.CharField(max_length=200)
    author = models.CharField(max_length=200)
    likes = models.IntegerField(default=0)

    class Meta:
        ordering = ['-likes']

    def __str__(self):
        return self.title

vline/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

# Create your models here.
class Message(models.Model):
    class BGColor(models.TextChoices):
        RED = 'R', _('Red')
        GREEN = 'G', _('Green')
        BLUE = 'B', _('Blue')
        YELLOW = 'Y', _('Yellow')
        DEFAULT = 'D', _('Default')
    
    bgcolor = models.CharField(max_length=1, choices=BGColor.choices, default=BGColor.DEFAULT)
    name = models.CharField(max_length=40)
    message = models.TextField()

    def __str__(self):
        return self.name

vline/forms.py
from django import forms
from .models import Message

class Message_Form(forms.ModelForm):
    class Meta:
        model = Message
        fields = '__all__'

akurdion/views.py
from django.shortcuts import render
from .models import Content

# Create your views here.
def index(request):
    items = Content.objects.all()
    context = {'items': items}
    return render(request,"akurdion.html", context)

donotopen/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm

def index(request):
    return render(request, 'donotopen/index.html')

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account created for {username}. We are happy to serve you.')
            return redirect('../login/')
    else:
        form = UserCreationForm()
    return render(request,'donotopen/register.html', {'form':form})

ijustnameitbookbecauseimnotcreative/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'book.html')

vline/views.py
from django.shortcuts import render, redirect
from .models import Message
from .forms import Message_Form
from random import choice

# Create your views here.
def index(request):
    if request.method == 'POST':
        query = request.POST['objectid']
        item = Message.objects.get(id=query)
        querycolor = request.POST['bgcolor']
        if querycolor == 'Random':
            item.bgcolor = choice("RGBY".replace(item.bgcolor, ""))
            item.save()
            return redirect('/vline')
        item.bgcolor = querycolor
        item.save()
        return redirect('/vline')
    items = Message.objects.all()
    context = {'items':items}
    return render(request, 'messages.html', context)

def addmessage(request):
    if request.method == 'POST':
        form = Message_Form(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/vline')
        else:
            return redirect('/vline')
    else:
        return render(request, 'addmessage.html')

akurdion/templates/akurdion.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Fesbuk</title>
    <link rel="icon" href="https://assets.gitlab-static.net/uploads/-/system/project/avatar/18034362/facebook-dating-1200x1200.jpg">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src=//ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js></script>
        <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
        <!-- <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script> -->
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</head>
<body class="bg-light">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark justify-content-between">
        <a class="navbar-brand" href="/vline">Fesbuk</a>
        <div class="custom-control custom-switch" id="switch">
            <input type="checkbox" class="custom-control-input" id="customSwitches">
            <label class="custom-control-label" for="customSwitches"></label>
        </div>
    </nav>
    <div class="container-fluid" style="margin-top: 10px">
        <div class="accordion" id="sortable">
            {% for item in items %}
            <div class="card bg-dark text-light">
                <div class="card-header" id="heading{{item.id}}">
                    <div class="row">
                        <div class="col-sm-8" id="button{{item.id}}" type="button" data-toggle="collapse" data-target="#collapse{{item.id}}" aria-expanded="false" aria-controls="collapse{{item.id}}">
                            <h2 class="mb-0">{{item.title}}</h2>
                        </div>
                        <div class="col-sm" style="display:flex; justify-content: flex-end;">
                            <button class="btn btn-success">Up</button>
                            <button class="btn btn-danger" style="margin-left: 10px;">Down</button>
                        </div>
                    </div>
                </div>
                
                <div id="collapse{{item.id}}" class="collapse" aria-labelledby="heading{{item.id}}">
                    <div class="card-body">
                        {{item.content}}
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    <script type="text/javascript">
        $("#sortable").sortable();
        $('.col-sm').children().click(function (e) {
            var $div = $(this).closest('.card');
            if (jQuery(e.target).is('.btn.btn-danger')) {
                $div.next('.card').after($div);
            } else {
                $div.prev('.card').before($div);
            }
        });
        $("#customSwitches").click(function (e) {
            var $body = $("body");
            if ($body.attr("class") == "bg-dark") {
                $body.attr("class", "bg-light");
                $("nav").attr("class", "navbar navbar-expand-lg navbar-dark bg-dark justify-content-between")
                $("#sortable").children().attr("class", "card bg-dark text-light")
            } else {
                $body.attr("class", "bg-dark");
                $("nav").attr("class", "navbar navbar-expand-lg navbar-light bg-light justify-content-between")
                $("#sortable").children().attr("class", "card bg-light text-dark")
            }
        });
    </script>
</body>
</html>

donotopen/templates/donotopen/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Fesbuk</title>
    <link rel="icon" href="https://assets.gitlab-static.net/uploads/-/system/project/avatar/18034362/facebook-dating-1200x1200.jpg">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</head>
<body>
    <div class="container text-center mt-5 pt-5">
    {% if user.is_authenticated %}
        <h1>welcome back, master {{ user.username }}</h1>
        <img src='{{user.usercustom.image}}'>
        <a href="{% url 'donotopen:logout' %}"><h3 class="mt-5">get me out</h3></a>
    {% else %}
        <h1>who are you?</h1>
        <a href="{% url 'donotopen:login' %}"><h3 class="mt-5">let me in</h3></a>
    {% endif %}
    </div>
</body>
</html>

donotopen/templates/donotopen/login.html
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Fesbuk</title>
    <link rel="icon" href="https://assets.gitlab-static.net/uploads/-/system/project/avatar/18034362/facebook-dating-1200x1200.jpg">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</head>
<body>
    <div class="container mt-5 pt-5">
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">{{ message }}</div>
        {% endfor %}
    {% endif %}
        <div class=" border border-dark p-4 rounded mb-4">
            <form method="POST">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">
                        Login
                    </legend>
                    {{ form|crispy }}
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-outline-dark" type="submit">
                        Sign In
                    </button>
                </div>
            </form>
            <div class="border-top pt-3">
                <small class="text-muted">
                    Don't have an account? What are you waiting for? <a href="{% url 'donotopen:register' %}">Register</a> now. Do it now
                </small>
            </div>
        </div>
    </div>
</body>
</html>

donotopen/templates/donotopen/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Fesbuk</title>
    <link rel="icon" href="https://assets.gitlab-static.net/uploads/-/system/project/avatar/18034362/facebook-dating-1200x1200.jpg">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</head>
<body>
    <div class="container text-center mt-5 pt-5">
        <h1>as you wish, master</h1>
        <small class="text-muted">
            you have successfully logged out, <a href="{% url 'donotopen:index' %}">return to homepage</a> or <a href="{% url 'donotopen:login' %}">return to login</a>
        </small>
    </div>
</body>
</html>

donotopen/templates/donotopen/register.html
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Fesbuk</title>
    <link rel="icon" href="https://assets.gitlab-static.net/uploads/-/system/project/avatar/18034362/facebook-dating-1200x1200.jpg">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</head>
<body>
    <div class="container mt-5">
        <div class=" border border-dark p-4 rounded mb-4">
            <form method="POST">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">
                        Register
                    </legend>
                    {{ form|crispy }}
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-outline-dark" type="submit">
                        Sign In
                    </button>
                </div>
            </form>
            <div class="border-top pt-3">
                <small class="text-muted">
                    Have an account? What are you doing here? <a href="{% url 'donotopen:login' %}">Login</a> now
                </small>
            </div>
        </div>
    </div>
</body>
</html>

ijustnameitbookbecauseimnotcreative/templates/book.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src=//ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <title>Books</title>
</head>
<body>
    <header class="d-flex flex-column flex-md-row align-items-md-center p-5 bg-light">
        <div class="pt-md-3 pb-md-4">
            <h1 class="bd-title mt-0">Books</h1>
            <p class="bd-lead">Find a book that suits your need!</p>
            <form class="form-inline" id="searchbar">
                <div class="form-group">
                <input type="search" class="form-control" id="search" placeholder="Mein Kampf" name="search" style="margin-right: 10px;">
                <button class="btn btn-primary" id="searchbtn">Search</button>
                </div>
            </form>
            <button class="btn btn-success">Top 5 Most liked book</button>
        </div>
    </header>
    <div class="container-fluid">
        
        <div class="row" id="result">
            
        </div>
    </div>
</body>
<script type="text/javascript" src="{% static 'scripts.js' %}"></script>
</html>

vline/templates/addmessage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Fesbuk</title>
    <link rel="icon" href="https://assets.gitlab-static.net/uploads/-/system/project/avatar/18034362/facebook-dating-1200x1200.jpg">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="/vline">Fesbuk</a>
    </nav>
    <div class="container-fluid" style="margin-top: 10px">
        <form id="form" method="POST">
            {% csrf_token %}
            {{ schedule_form }}
            <label for="id_nama">Nama: </label>
            <input type="text" name="name" class="form-control" maxlength="40" id="id_nama" required>
            <label for="id_pesan">Pesan: </label>
            <input type="text" name="message" class="form-control" id="id_pesan" required>
            <label for="id_bgcolor">Warna: </label>
            <select id="id_bgcolor" name="bgcolor" class="form-control">
                <option value="R">Merah</option>
                <option value="G">Hijau</option>
                <option value="B">Biru</option>
                <option value="Y">Kuning</option>
            </select>
            <button type="submit" class="btn btn-primary" style="margin-top: 10px;" id="submit">Kirim</button>
        </form>
    </div>
</body>
</html>

vline/templates/messages.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Fesbuk</title>
    <link rel="icon" href="https://assets.gitlab-static.net/uploads/-/system/project/avatar/18034362/facebook-dating-1200x1200.jpg">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="/vline">Fesbuk</a>
    </nav>
    <div class="container-fluid" style="margin-top: 10px">
    {% for item in items %}
    {% if item.bgcolor == "R" %}
        <div class="card border-secondary bg-danger mb-3">
    {% elif item.bgcolor == "B" %}
        <div class="card border-secondary bg-primary mb-3">
    {% elif item.bgcolor == "G" %}
        <div class="card border-secondary bg-success mb-3">
    {% elif item.bgcolor == "Y" %}
        <div class="card border-secondary bg-warning mb-3">
    {% else %}
        <div class="card border-secondary mb-3">
    {% endif %}
            <div class="card-header">{{item.name}} said</div>
            <div class="card-body text-secondary">
                <p class="card-text">"{{item.message}}"</p>
            </div>
            <form id="form" method="POST">
                {% csrf_token %}
                <input type = "hidden" name="objectid" value="{{item.id}}">
                <button type="submit" class="btn btn-danger" style="margin: 10px; padding:10px;" id="red" name="bgcolor" value="R"></button>
                <button type="submit" class="btn btn-success" style="margin: 10px; padding:10px;" id="green" name="bgcolor" value="G"></button>
                <button type="submit" class="btn btn-primary" style="margin: 10px; padding:10px;" id="blue" name="bgcolor" value="B"></button>
                <button type="submit" class="btn btn-warning" style="margin: 10px; padding:10px;" id="yellow" name="bgcolor" value="Y"></button>
                <button type="submit" class="btn btn-secondary" style="margin-left:10px;height: 23px; font-size:10px;" id="submit" name="bgcolor" value="Random">Random</button>
            </form>
        </div>
    {% endfor %}
    <a href="addmessage">
        <button type="button" class="btn btn-outline-secondary" style="width: 100%; margin-bottom:10px">Saya mau kirim pesan</button>
    </a>
    </div>
</body>
</html>